/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pointclouds_bodyparts_Grabber */

#ifndef _Included_org_pointclouds_bodyparts_Grabber
#define _Included_org_pointclouds_bodyparts_Grabber
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pointclouds_bodyparts_Grabber
 * Method:    cacheIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pointclouds_bodyparts_Grabber_cacheIds
  (JNIEnv *, jclass);

/*
 * Class:     org_pointclouds_bodyparts_Grabber
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pointclouds_bodyparts_Grabber_free
  (JNIEnv *, jobject);

/*
 * Class:     org_pointclouds_bodyparts_Grabber
 * Method:    createOpenNIGrabber
 * Signature: ()Lorg/pointclouds/bodyparts/Grabber;
 */
JNIEXPORT jobject JNICALL Java_org_pointclouds_bodyparts_Grabber_createOpenNIGrabber
  (JNIEnv *, jclass);

/*
 * Class:     org_pointclouds_bodyparts_Grabber
 * Method:    createFileGrabber
 * Signature: (Ljava/lang/String;)Lorg/pointclouds/bodyparts/Grabber;
 */
JNIEXPORT jobject JNICALL Java_org_pointclouds_bodyparts_Grabber_createFileGrabber
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_pointclouds_bodyparts_Grabber
 * Method:    isConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_pointclouds_bodyparts_Grabber_isConnected
  (JNIEnv *, jobject);

/*
 * Class:     org_pointclouds_bodyparts_Grabber
 * Method:    getFrame
 * Signature: (Lorg/pointclouds/bodyparts/Cloud;)V
 */
JNIEXPORT void JNICALL Java_org_pointclouds_bodyparts_Grabber_getFrame
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_pointclouds_bodyparts_Grabber
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pointclouds_bodyparts_Grabber_start
  (JNIEnv *, jobject);

/*
 * Class:     org_pointclouds_bodyparts_Grabber
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pointclouds_bodyparts_Grabber_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
