/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pointclouds_bodyparts_Application */

#ifndef _Included_org_pointclouds_bodyparts_Application
#define _Included_org_pointclouds_bodyparts_Application
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pointclouds_bodyparts_Application
 * Method:    setenv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_pointclouds_bodyparts_Application_setenv
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
