/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pointclouds_bodyparts_Cloud */

#ifndef _Included_org_pointclouds_bodyparts_Cloud
#define _Included_org_pointclouds_bodyparts_Cloud
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_pointclouds_bodyparts_Cloud
 * Method:    cacheIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pointclouds_bodyparts_Cloud_cacheIds
  (JNIEnv *, jclass);

/*
 * Class:     org_pointclouds_bodyparts_Cloud
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pointclouds_bodyparts_Cloud_create
  (JNIEnv *, jobject);

/*
 * Class:     org_pointclouds_bodyparts_Cloud
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_pointclouds_bodyparts_Cloud_free
  (JNIEnv *, jobject);

/*
 * Class:     org_pointclouds_bodyparts_Cloud
 * Method:    readColors
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_org_pointclouds_bodyparts_Cloud_readColors
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     org_pointclouds_bodyparts_Cloud
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_pointclouds_bodyparts_Cloud_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_pointclouds_bodyparts_Cloud
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_pointclouds_bodyparts_Cloud_getWidth
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
